### ISSUE TITLE
CUDA layout

### ISSUE THREAD

**Issue by Liuhp133** [DaiShiResearch/TransNeXt#7]
This issue may occur when using transnext_cuda. py, but it does not occur when using transnext_cative. py, provided that the attention has already been installed.

Traceback (most recent call last):
  File "/home/omnisky/sdf/ljx/TransNeXt/train_kfold.py", line 115, in <module>
    train_loss, train_acc = train_one_epoch(model, criterion, optimizer, train_loader)
  File "/home/omnisky/sdf/ljx/TransNeXt/train_kfold.py", line 48, in train_one_epoch
    outputs = model(inputs)
  File "/home/omnisky/anaconda3/envs/transnext/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/omnisky/anaconda3/envs/transnext/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/omnisky/sdf/ljx/TransNeXt/classification/transnext_cuda.py", line 453, in forward
    x = self.forward_features(x)
  File "/home/omnisky/sdf/ljx/TransNeXt/classification/transnext_cuda.py", line 445, in forward_features
    x = blk(x, H, W, relative_pos_index, relative_coords_table)
  File "/home/omnisky/anaconda3/envs/transnext/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/omnisky/anaconda3/envs/transnext/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/omnisky/sdf/ljx/TransNeXt/classification/transnext_cuda.py", line 314, in forward
    x = x + self.drop_path(self.attn(self.norm1(x), H, W, relative_pos_index, relative_coords_table))
  File "/home/omnisky/anaconda3/envs/transnext/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/omnisky/anaconda3/envs/transnext/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/omnisky/sdf/ljx/TransNeXt/classification/transnext_cuda.py", line 195, in forward
    attn_local = sw_qkrpb_cuda.apply(q_norm_scaled.contiguous(), F.normalize(k_local, dim=-1).contiguous(), self.relative_pos_bias_local,
  File "/home/omnisky/anaconda3/envs/transnext/lib/python3.10/site-packages/torch/autograd/function.py", line 553, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/omnisky/sdf/ljx/TransNeXt/classification/transnext_cuda.py", line 18, in forward
    attn_weight = swattention.qk_rpb_forward(query, key, rpb, height, width, kernel_size, CUDA_NUM_THREADS)
RuntimeError: Unknown layout

![image](https://github.com/DaiShiResearch/TransNeXt/assets/122658071/951dc75e-0fcb-4c46-92be-3609137179ca)

**Comment by timesd** [comment]
The information provided is currently insufficient for me to determine the cause of the error. However, this issue should be due to the cuda extension module of the swattention package not working properly. I suggest you test this module separately to verify this. A common error of this module is that the CUDA version of the system used to compile the swattention package is inconsistent with the CUDA version used by torch. Therefore, I suggest you use `nvcc -V` to check whether the CUDA version of the system and the CUDA version that torch currently depends on are consistent.

**Comment by DaiShiResearch** [comment]
The information provided is currently insufficient for me to determine the cause of the error. However, this issue should be due to the cuda extension module of the swattention package not working properly. I suggest you test this module separately to verify this. A common error of this module is that the CUDA version of the system used to compile the swattention package is inconsistent with the CUDA version used by torch. Therefore, I suggest you use `nvcc -V` to check whether the CUDA version of the system and the CUDA version that torch currently depends on are consistent.

**Comment by Liuhp133** [comment]
I'm experiencing an issue with the swattention package related to CUDA compatibility, despite having CUDA 11.8 installed on my system and using PyTorch torch 2.2.1+cu118. The CUDA extension module is not functioning as expected.
![image](https://github.com/DaiShiResearch/TransNeXt/assets/122658071/e429f5a5-f5b6-44b2-aa6b-98ccd9eaa5c2)
![image](https://github.com/DaiShiResearch/TransNeXt/assets/122658071/df86fd89-9ec6-4737-9f00-cb9532d5a572)

**Comment by DaiShiResearch** [comment]
Another point to note is that if you have installed multiple versions of CUDA on your machine, or have switched CUDA versions, the previously installed swattention package needs to be uninstalled and recompiled. If it still doesn’t work, it is recommended to test this in a cleaner environment, or use the docker container provided by Nvidia. I also hope that you can follow up and provide feedback in this post after finding the cause, which may help others who encounter similar situations in the future.

**Comment by YHCks** [comment]
![Image](https://github.com/user-attachments/assets/0c8ec5a5-379f-437d-8892-d204768f1007)
我遇到了差不多的问题，我在安装完成attention后出现了上述错误，我用dependencies分析attention的.pyd
文件遇到了

![Image](https://github.com/user-attachments/assets/0be882c2-7251-4edd-b8eb-a63aec7573b0)缺失与

![Image](https://github.com/user-attachments/assets/1259e79b-a76c-4ac1-a996-1c59325435ea)缺失的问题，请问这个是什么原因
